name: Simple Hello Workflow

on:
  push:
    branches:
      - main
      - master


jobs:
 
  say_hello:
   
    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v4

      
      - name: Print Hello Message
        run: echo "Hello GitHub Actions"
